Electroid/SportPaper

patches/api/0092-Add-cave-frequency-API.patch
patches/server/0174-Add-cave-frequency-API.patch
scripts/importmcdev.sh

This PR allows for the internal variables used to control cave system frequency to be modified. My main mechanism for doing this on the API end is by adding a variable to the `WorldCreator` class which can be modified prior to world generation. From there, this variable is passed to modified NMS classes to `WorldData`, which is a class that stores persistent data for a world. The NMS cave generator class was then modified to check the `WorldData` class to obtain cave frequency information. The good thing about the `WorldData` approach is that I'm able to store the modified cave frequency within the NBTTags for the world, so the cave frequency change is persistent, even when new chunks are generated, as long as this verison of SportPaper is used.
I tested out a couple of approaches for …

Add cave frequency API

---

patches/server/0183-Fix-NamedEntitySpawn-not-initializing-data-watcher.patch

Fixes an error in the `PacketPlayOutNamedEntitySpawn` class where the data watcher is not initialized inside the constructor causing a `NullPointerException`

Fix NamedEntitySpawn not initializing data watcher

---

patches/api/0098-Allow-plugins-to-append-custom-data-in-server-ping.patch
patches/server/0184-Allow-plugins-to-append-custom-data-in-server-ping.patch
scripts/importmcdev.sh

This will allow [PGM](https://github.com/Electroid/PGM) to expose extra information, such as current and next map, or amount of participating and observing players. Might be useful for the oc.tc website showing current and next map, or custom clients.
Related: https://github.com/ProjectEnyo/projectenyo.github.io/pull/4#issuecomment-569471250

Allow plugins to append custom data in server ping

---

patches/server/0185-Speed-up-chunk-unloading.patch

- Changes unload queue to a [LongOpenHashSet](http://fastutil.di.unimi.it/docs/it/unimi/dsi/fastutil/longs/LongOpenHashSet.html)
- Removes some redundant queue checks. 
- Moves some unload queue checks out of places where the chunk would never be in the queue to begin with.

Speed up chunk unloading

---

patches/server/0188-Implement-customizable-knockback-config-options-and-.patch

Patch included in Walrus SportPaper that adds customizable knockback. This patch, however, uses Bukkit default knockback as its defaults as opposed to Shiny's patch which had some tweaked values. Full credit to Shiny for the config API and Austin for the knockback command.

Implemented customizable knockback config options and commands

---

patches/server/0190-Add-option-to-remove-randomness-in-arrow-damage.patch
sportpaper.yml

What the title says. The option is disabled by default (just so existing SportPaper servers don't see their behavior changed) but can be enabled by changing `include-randomness-in-arrow-damage: true` to `include-randomness-in-arrow-damage: false`. Here's a demonstration:
With randomness in arrow damage: https://i.imgur.com/Rpf5ZRE.gif
Without randomness in arrow damage: https://i.imgur.com/rg8rZyT.gif
Full credit to @mattarnold98, author of the [original patch](https://github.com/WalrusNetwork/SportPaper/commit/dacb01f2856a190e4b04fcf017b9d4d5d332832b) in the Stratus/Walrus SportPaper.
Signed-off-by: Indicado <indicado@walrus.gg>

Add option to remove randomness in arrow damage

---

patches/server/0193-Update-MySQL-Connector.patch

The MySQL connector is version 5.1.14, which is really old and can't connect to the latest version of MySQL, so this PR updates it to version 8.0.22.

Update MySQL Connector

---

patches/server/0003-Agree-to-the-Eula-by-default.patch

Since the EULA is accepted by default, there is no reason to create the eula.txt file.

Don't create eula.txt

---

patches/server/0191-Prevent-1.7-players-glitching-in-carpet.patch
sportpaper.yml

The original commit makes it so 1.7 clients can get glitched in carpets if they jump on them at weird angles, it is relatively easy to replicate on this commit and impossible to do on the previous commit

Revert "Make carpet fix toggleable, and always produce a bounding box"

---

patches/api/0101-Expose-client-disconnect-reason.patch
patches/server/0195-Expose-client-disconnect-reason.patch

Adds `getDisconnectReason()` to `PlayerQuitEvent` which exposes the reason message printed to console and displayed in the client.

Expose client disconnect reason

---

patches/api/0101-Make-unknown-and-internal-command-messages-customisa.patch
patches/server/0193-Make-unknown-and-internal-command-messages-customisa.patch
sportpaper.yml

Makes the unknown command and internal error messages customisable in PlayerCommandPreprocessEvent. Useful for multi-language servers.

Make unknown command and internal error messages customisable

---

patches/api/0102-Make-unknown-and-internal-command-messages-customisa.patch
patches/api/0103-Make-PlayerEvent-async-constructor-public.patch
patches/server/0194-Update-MySQL-Connector.patch
patches/server/0195-Don-t-store-merchant-recipes-with-invalid-data.patch
patches/server/0196-Expose-client-disconnect-reason.patch
patches/server/0198-Fixed-chunk-memory-leak.patch
patches/server/0199-Limit-CraftChatMessage-iterations.patch
patches/server/0200-Don-t-use-force-unload-for-keep-spawn-setting-change.patch
patches/server/0201-Cache-block-break-animation-packet.patch
patches/server/0202-Fix-EntityKnockbackByEntityEvent.patch

This PR has these patches:
- Chunk memory leak fix (closes #40, patch provided by @LewUwU)
- CraftChatMessage-iteration (closes #40, patch provided by @LewUwU)
- Don't use force unload for keep spawn setting change (closes #13, patch provided by @LewUwU)
- Caching block break animation packet (before it would create the same packet for each player)
- Fix EntityKnockbackByEntityEvent (closes #50). Now it's called for explosions too and the "hitBy" variable is set to the actual entity that did the knockback
- Make PlayerEvent async constructor public. For some reason it was package-private.

Several patches

---

patches/server/0203-Always-delete-UserCache-on-error.patch

Sometimes the server can't start because of UserCache corruption. This fixes it.

Always delete UserCache on error

---

patches/server/0204-Fix-EntityKnockbackByEntityEvent.patch

The d14 variable is sometimes 0, and dividing something by 0 in Java results in NaN, so that's where the invalid move packets came from.
Closes #83.

Actually fix EntityKnockbackByEntityEvent

---

patches/server/0206-Add-API-for-custom-format-loaders.patch
patches/server/0208-Disable-log4j-message-formatting.patch
patches/server/0209-Upgrade-log4j-version.patch

CraftBukkit's 1.8.8 branch has been updated with these two patches following the discovery/announcement of the log4j exploit. Ideally, upstream Paper 1.8.8 would have the CraftBukkit submodule updated to the latest commit and then we could update the Paper submodule here, but perhaps this is preferred since it is quicker.

Add upstream CraftBukkit 1.8.8 log4j patches

---

scripts/baseremap.sh

The previous download location seems to be down indefinitely. This link is direct from Mojang for the 1.8.8 server.

Fix invalid vanilla jar download link

---

patches/server/0216-Prevent-desync-with-some-packets-that-use-entity-id-.patch

If a player has entity id 0 (first one to join), some of this packets will lack informations, for example with PacketPlayOutSpawnEntity on arrows, the constructor is taking (Entity, entity type, entity id of the shooter), if owner of projectile has entity id 0, then the packet will lack motion information so the arrow will look buggy on client view, see in video,
quick fix is to start id from 1 instead of 0
https://www.youtube.com/watch?v=bJ8ilYxwt0k

Prevent desync with some packets that use entity id and check for 0

---

.github/workflows/build.yml
.gitmodules
patches/api/0104-Resolve-build-issues-with-Java-17.patch
patches/server/0211-Add-events-for-water-source-creation.patch
patches/server/0212-Apply-explosion-knockback-to-projectiles.patch
patches/server/0213-Patch-Book-Exploits.patch
patches/server/0214-Update-to-Netty-4.1.x.patch
patches/server/0215-Set-cap-on-JDK-per-thread-native-byte-buffer-cache.patch
patches/server/0217-Resolve-build-issues-with-Java-17.patch
scripts/upstream.sh

This PR fixes issues with building SportPaper using Java 17, and switches the workflow over accordingly.
In order to build with Java 17, we need newer copies of SpecialSource and SpecialSource-2 than those provided in the Paper 1.8.8 branch's BuildData submodule from Spigot. As such, I have added a submodule in the repository root which points to the latest BuildData commit from Spigot. We copy the jars for SpecialSource and SpecialSource-2 from this submodule and overwrite them in the Paper submodule, once all of the Paper submodules are initialised.
Upstream BuildData also contains a newer version of Fernflower, however the format of the decompiled code differs from the version of Fernflower currently used, and therefore all patches would need reformatting. Since the version of …

Resolve build issues with Java 17

---

patches/server/0218-Add-setting-to-check-line-of-sight.patch
patches/server/0219-Make-critical-hits-configurable.patch
patches/server/0220-Optimize-networking-by-using-IP_TOS.patch
patches/server/0221-Add-Unix-domain-socket-support.patch
patches/server/0222-Fix-east-west-cannoning.patch

This PR contains several patches.
The first two have been deployed on Overcast Community's BOLT and Stratus Network for some time now. These permit hits to be dealt in combat without strict line of sight, and for the damage multipler of critical hits to be modified. I have cleaned up the former patch slightly compared to its deployed states, ensuring vanilla behaviour as default (potentially important for anticheats), but unless I made some error it should function as expected.
The remaining patches come from Paper itself or other Paper or Spigot forks. The simplest of these sets IP_TOS 0x18 for Netty; I'm not very knowledgeable as to what this entails but from what I have read it seems like a desirable network configuration option. Another, backported from modern Paper, adds Unix domain …

Upstream and/or backport miscellaneous patches

---

patches/api/0105-Add-internal-setMaxStackSize-method-for-materials.patch
patches/server/0223-Remove-hacky-stackable-buckets-code.patch
patches/server/0224-Make-dimension-field-non-final.patch

The patches in this PR allow for us to run SportPaper (with a patched PGM) on Java 17 and 21. The first commit comes from PandaSpigot and removes use of reflection for a stackable buckets patch added in Paper 1.8.8, while the second commit makes the `dimension` field in `WorldServer` non-final, which is relevant to running PGM on SportPaper with Java 17+.

Support for Java 17+

---

.github/workflows/build.yml

Obviously inspired by PGMDev/PGM#1316. I regularly get my copies of SportPaper from the actions tab (and most likely many others too), so I think this is important to keep everything up to date. 
It has been tested on my fork and builds without any issue and removes the Node 16 deprecation warnings.

Update v3 GH actions to v4

---

patches/server/0226-Readd-NPE-prevention-for-BlockDispenseEntityEvent.patch

NPE:
```
java.lang.NullPointerException: Cannot invoke "net.minecraft.server.v1_8_R3.Entity.getBukkitEntity()" because "entity" is null
at net.minecraft.server.v1_8_R3.DispenserRegistry$6.b(DispenserRegistry.java:93)
at net.minecraft.server.v1_8_R3.DispenseBehaviorItem.a(DispenseBehaviorItem.java:13)
at net.minecraft.server.v1_8_R3.BlockDispenser.dispense(BlockDispenser.java:86)
at net.minecraft.server.v1_8_R3.BlockDispenser.b(BlockDispenser.java:115)
at net.minecraft.server.v1_8_R3.WorldServer.a(WorldServer.java:683)
at net.minecraft.server.v1_8_R3.WorldServer.doTick(WorldServer.java:247)
at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:941)
at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:385)
at …
```

Fix NPE related to BlockDispenseEntityEvent

---

patches/server/0229-Use-TerminalConsoleAppender-for-console-improvements.patch
patches/server/0230-Use-Log4j-IOStreams-to-redirect-System.out-err-to-lo.patch
patches/server/0231-Use-AsyncAppender-to-keep-logging-IO-off-main-thread.patch

Depends on https://github.com/Electroid/SportPaper/pull/146 and https://github.com/Electroid/SportPaper/pull/147
1. Adopts TerminalConsoleAppender, which gives several console improvements
2. "Use Log4j IOStreams to redirect System.out/err to logger". This avoids sending empty lines on modern versions of Java.
3. "Use AsyncAppender to keep logging IO off main thread"; self-explanatory

Improve console and logging
